// Generated by scripts/build_tts_pronunciation_preferences.py.
// Existing CMU variants preferred by the corpus TTS voice; do not edit manually.
struct FOffgridAITtsPronunciationPreferenceRow
{
    const TCHAR* Word;
    const TCHAR* Phones;
    int32 ObservationCount;
    float PreferredShare;
};

static const FOffgridAITtsPronunciationPreferenceRow GTtsPronunciationPreferences[] =
{
    {TEXT("always"), TEXT("AO1 L W IY0 Z"), 5, 1.000000f},
    {TEXT("and"), TEXT("AE1 N D"), 134, 0.626866f},
    {TEXT("as"), TEXT("AE1 Z"), 4, 0.750000f},
    {TEXT("beaches"), TEXT("B IY1 CH IH0 Z"), 11, 1.000000f},
    {TEXT("can"), TEXT("K AH0 N"), 25, 0.680000f},
    {TEXT("enjoy"), TEXT("IH0 N JH OY1"), 6, 1.000000f},
    {TEXT("for"), TEXT("F ER0"), 61, 0.508197f},
    {TEXT("indigo"), TEXT("IH1 N D IH0 G OW2"), 9, 0.888889f},
    {TEXT("interesting"), TEXT("IH1 N T R IH0 S T IH0 NG"), 5, 1.000000f},
    {TEXT("is"), TEXT("IH1 Z"), 25, 1.000000f},
    {TEXT("sandwiches"), TEXT("S AE1 M W IH0 CH IH0 Z"), 22, 0.681818f},
    {TEXT("sounds"), TEXT("S AW1 N Z"), 13, 0.615385f},
    {TEXT("to"), TEXT("T AH0"), 41, 0.682927f},
    {TEXT("violet"), TEXT("V AY1 L IH0 T"), 9, 0.666667f},
    {TEXT("what"), TEXT("HH W AH1 T"), 23, 0.869565f},
    {TEXT("what'll"), TEXT("HH W AH1 T AH0 L"), 9, 1.000000f},
    {TEXT("what's"), TEXT("HH W AH1 T S"), 4, 1.000000f},
    {TEXT("which"), TEXT("HH W IH1 CH"), 11, 0.818182f},
    {TEXT("with"), TEXT("W IH1 TH"), 17, 0.823529f},
    {TEXT("your"), TEXT("Y UH1 R"), 10, 1.000000f},
};
