#!/usr/bin/env python3
"""Build portable phone-duration priors from approved MFA alignments."""

from __future__ import annotations

import csv
import hashlib
import json
import re
import statistics
from collections import defaultdict
from pathlib import Path


MIN_POSITION_OBSERVATIONS = 8
MIN_PHONE_SECONDS = 0.025
MAX_PHONE_SECONDS = 0.250


def base_phone(phone: str) -> str:
    return re.sub(r"\d", "", phone)


def position_name(index: int, count: int) -> str:
    if count == 1:
        return "single"
    if index == 0:
        return "initial"
    if index + 1 == count:
        return "final"
    return "medial"


def read_observations(gold_root: Path) -> list[tuple[str, str, str, float]]:
    observations: list[tuple[str, str, str, float]] = []
    for case_dir in sorted(path for path in gold_root.iterdir() if path.is_dir()):
        phones_path = case_dir / "phones.csv"
        if not phones_path.exists():
            continue
        by_word: dict[int, list[dict[str, str]]] = defaultdict(list)
        with phones_path.open(newline="", encoding="utf-8-sig") as handle:
            for row in csv.DictReader(handle):
                by_word[int(row.get("word_index", -1))].append(row)
        for phones in by_word.values():
            if any((row.get("phone") or "").lower() == "spn" for row in phones):
                continue
            for index, row in enumerate(phones):
                phone = row.get("phone") or ""
                base = base_phone(phone)
                if not base:
                    continue
                duration = max(float(row.get("end") or 0.0) - float(row.get("start") or 0.0), 0.0)
                if duration <= 0.0:
                    continue
                observations.append((case_dir.name, base, position_name(index, len(phones)), duration))
    return observations


def fit(observations: list[tuple[str, str, str, float]]) -> tuple[dict[str, float], dict[tuple[str, str], float]]:
    by_base: dict[str, list[float]] = defaultdict(list)
    by_position: dict[tuple[str, str], list[float]] = defaultdict(list)
    for _, base, position, duration in observations:
        by_base[base].append(duration)
        by_position[(base, position)].append(duration)
    base_priors = {
        base: min(max(statistics.median(values), MIN_PHONE_SECONDS), MAX_PHONE_SECONDS)
        for base, values in by_base.items()
    }
    position_priors = {
        key: min(max(statistics.median(values), MIN_PHONE_SECONDS), MAX_PHONE_SECONDS)
        for key, values in by_position.items()
        if len(values) >= MIN_POSITION_OBSERVATIONS
    }
    return base_priors, position_priors


def evaluate(
    observations: list[tuple[str, str, str, float]],
    base_priors: dict[str, float],
    position_priors: dict[tuple[str, str], float],
) -> dict[str, float]:
    base_errors: list[float] = []
    position_errors: list[float] = []
    for _, base, position, duration in observations:
        if base not in base_priors:
            continue
        base_errors.append(abs(base_priors[base] - duration) * 1000.0)
        predicted = position_priors.get((base, position), base_priors[base])
        position_errors.append(abs(predicted - duration) * 1000.0)
    return {
        "observation_count": len(position_errors),
        "base_mae_ms": sum(base_errors) / max(len(base_errors), 1),
        "base_position_mae_ms": sum(position_errors) / max(len(position_errors), 1),
    }


def write_cpp(
    path: Path,
    base_priors: dict[str, float],
    position_priors: dict[tuple[str, str], float],
) -> None:
    position_codes = {"single": 0, "initial": 1, "medial": 2, "final": 3}
    lines = [
        "// Generated by scripts/build_phone_duration_priors.py.",
        "// Median MFA durations for this TTS family; do not edit manually.",
        "struct FOffgridAIPhoneDurationPriorRow",
        "{",
        "    const TCHAR* BasePhone;",
        "    int32 WordPosition;",
        "    float Seconds;",
        "};",
        "",
        "static const FOffgridAIPhoneDurationPriorRow GPhoneDurationPriors[] =",
        "{",
    ]
    for base, seconds in sorted(base_priors.items()):
        lines.append(f'    {{TEXT("{base}"), -1, {seconds:.6f}f}},')
    for (base, position), seconds in sorted(position_priors.items()):
        lines.append(
            f'    {{TEXT("{base}"), {position_codes[position]}, {seconds:.6f}f}},'
        )
    lines.extend(["};", ""])
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    observations = read_observations(root / "inputs/gold")
    train = [
        row for row in observations
        if int(hashlib.sha1(row[0].encode("utf-8")).hexdigest()[:8], 16) % 5 != 0
    ]
    test = [
        row for row in observations
        if int(hashlib.sha1(row[0].encode("utf-8")).hexdigest()[:8], 16) % 5 == 0
    ]
    train_base, train_position = fit(train)
    heldout = evaluate(test, train_base, train_position)
    base_priors, position_priors = fit(observations)
    write_cpp(
        root / "offgrid_dropin/Private/Lipsync/OffgridAIPhoneDurationPriors.inl",
        base_priors,
        position_priors,
    )
    report = {
        "minimum_position_observations": MIN_POSITION_OBSERVATIONS,
        "observation_count": len(observations),
        "base_prior_count": len(base_priors),
        "position_prior_count": len(position_priors),
        "heldout": heldout,
    }
    (root / "docs/phone_duration_priors.json").write_text(
        json.dumps(report, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(
        f"Generated {len(base_priors)} base and {len(position_priors)} position priors; "
        f"heldout MAE {heldout['base_mae_ms']:.2f} -> {heldout['base_position_mae_ms']:.2f} ms"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
